### PR TITLE
qwik-query type safety

### PR DESCRIPTION
**Pull request by graddotdev**

### CODE REVIEW

**Review by gioboa — APPROVED** [review]
Thanks @gradddev it looks nice

**Comment by graddotdev** [comment]
@TkDodo, In qwik, we have to wrap each function in the QRL and then unwrap them back to use with query-core, but I'm stuck on a problem related to the `NonFunctionGuard` type. Could you take a look at the problem in this playground: https://tsplay.dev/WKbqKm?

**Comment by gioboa** [comment]
@gradddev Thanks for your amazing help 🚀

**Comment by TkDodo** [comment]
@gradddev Even if we omit placeholderData, we'll get a different, but similar error:

```
Types of property 'queryKey' are incompatible.
    Type 'DeQRLify<QRLify<TQueryKey>> | undefined' is not assignable to type 'TQueryKey | undefined'.
```

looking at the properties of `options`, they are all joined with `| DeQRLify`, for example, InitialData is:

```
InitialDataFunction<TQueryData> | DeQRLify<QRLify<TQueryData>> | undefined
```

I don't think this is supposed to be assignable to `QueryOptions['initialData']` ...

**Comment by graddotdev** [comment]
@TkDodo, got it, thanks. I'll see what I can do about that.

**Pull request closed without merging**
